image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 8000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: >
    pip install -r requirements.txt &&
    ./manage.py initialsetup &&
    ./manage.py preparestatic
  command: ./manage.py runserver